apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: weathersation-api
  namespace: swh
spec:
  secretName: weatherstation-api-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "weatherstation.sharky.live"
  dnsNames:
  - "weatherstation.sharky.live"