apiVersion: v1
kind: Secret
metadata:
  name: weatherstation-secret
  namespace: swh
type: Opaque
data:
  username: d2VhdGhlcnN0YXRpb24= 
  password: cGVxcnp6RGtYNXZDUDNHUQ==
  PW: c2VjUFcxMjM0NTZWZXJ5U2VjdXJlV2VhdGhlclN0YXRpb25QYXNzd29yZA== 
